version: '3.8'
services:
  db:
    image: postgres:15
    container_name: admin-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: pojokherbal
      POSTGRES_PASSWORD: djanthi
      POSTGRES_DB: admin
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgweb:
    image: sosedoff/pgweb
    container_name: admin-pgweb
    ports:
      - '8081:8081'
    environment:
      - DATABASE_URL=postgres://pojokherbal:djanthi@localhost:5432/admin
    depends_on:
      - db

volumes:
  pgdata:
